### ISSUE TITLE
Tooltips are too short

### ISSUE THREAD

**Issue by hadley** [htmlwidgets/sparkline#4]
![screen shot 2015-01-06 at 3 18 03 pm](https://cloud.githubusercontent.com/assets/4196/5636387/4374c19e-95b7-11e4-808c-07973fd0df41.png)

Possibly because I have retina display

**Comment by ramnathv** [comment]
I presume you are using `bootstrap`. This is a well known issue using `sparkline` with `bootstrap` and there is a [simple css fix](http://stackoverflow.com/questions/18894820/jquery-sparklines-and-twitter-bootstrap-3-tooltip-style-overrides), which I will include when I push code to this repo next time.

**Comment by ramnathv** [comment]
- [ ] add css to fix tooltips when rendered with bootstrap

```css
.jqstooltip {
  -webkit-box-sizing: content-box;
  -moz-box-sizing: content-box;
  box-sizing: content-box;
}
```
